### ISSUE TITLE
Support regirsty url as env variable

### ISSUE THREAD

**Issue by Jiri-Stary** [getyourguide/dependabutler#80]
currently only username and passoword are supporte not the url itself:

```
registries:
  docker:
    jfrog-registry:
      type: docker-registry
      url: "${{secrets.JFROG_ARTIFACTORY_URL}}"
      username: "${{secrets.ARTIFACTORY_USERNAME}}"
      password: "${{secrets.ARTIFACTORY_PASSWORD}}"
      url-match-required: true


```

2025/06/12 13:54:44 ERROR default registry has invalid URL ${{secrets.JFROG_ARTIFACTORY_URL}}
